/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import Controlador.CristoTubeClientController;
import java.io.File;
import javax.swing.SwingWorker;

/**
 *
 * @author Jaime
 */
public class Login extends javax.swing.JFrame {
    public static CristoTubeClientController controller;
    public static String listaVideos;
    public static String loginUsuario;
    public static File fileSubirVideo;
    public static boolean terminarRecibir = false;
    /**
     * Creates new form Login
     */
    public Login() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Logo = new javax.swing.JLabel();
        login = new javax.swing.JLabel();
        password = new javax.swing.JLabel();
        introducirLogin = new javax.swing.JTextField();
        entrar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        textAreaDebug = new javax.swing.JTextArea();
        serverName = new javax.swing.JLabel();
        introducirServerName = new javax.swing.JTextField();
        portNumber = new javax.swing.JLabel();
        introducirPortNumber = new javax.swing.JTextField();
        registro = new javax.swing.JButton();
        introducirPassword = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/LogoCT copia.png"))); // NOI18N
        getContentPane().add(Logo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 480, 230));

        login.setText("Login");
        getContentPane().add(login, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 270, 40, 20));

        password.setText("Password");
        getContentPane().add(password, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 340, 60, 20));
        getContentPane().add(introducirLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 270, 80, -1));

        entrar.setText("Entrar");
        entrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                entrarActionPerformed(evt);
            }
        });
        getContentPane().add(entrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 380, 110, 40));

        textAreaDebug.setColumns(20);
        textAreaDebug.setRows(5);
        jScrollPane1.setViewportView(textAreaDebug);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 516, 590, 160));

        serverName.setText("Server Name");
        getContentPane().add(serverName, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 270, 70, 20));

        introducirServerName.setText("localhost");
        getContentPane().add(introducirServerName, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 270, 80, -1));

        portNumber.setText("Port Number");
        getContentPane().add(portNumber, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 340, 70, 20));

        introducirPortNumber.setText("8080");
        getContentPane().add(introducirPortNumber, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 340, 80, -1));

        registro.setText("Registro");
        registro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registroActionPerformed(evt);
            }
        });
        getContentPane().add(registro, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 440, 110, 40));
        getContentPane().add(introducirPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 340, 80, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void entrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_entrarActionPerformed
        controller = new CristoTubeClientController(introducirServerName.getText(), Integer.parseInt(introducirPortNumber.getText()));
        String cadenaLogin = "PROTOCOLCRISTOTUBE1.0#LOGIN#" 
                + introducirLogin.getText() 
                + "#" + introducirPassword.getText();
        loginUsuario = introducirLogin.getText();
        final SwingWorker worker = new SwingWorker() {
            @Override
            protected Object doInBackground() throws Exception {
                controller.conectar(textAreaDebug, cadenaLogin);
                return null;
            }
        };
        worker.execute();
    }//GEN-LAST:event_entrarActionPerformed

    private void registroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registroActionPerformed
        Registro registro = new Registro(controller, textAreaDebug);
        registro.setVisible(true);
    }//GEN-LAST:event_registroActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new Login().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Logo;
    private javax.swing.JButton entrar;
    private javax.swing.JTextField introducirLogin;
    private javax.swing.JPasswordField introducirPassword;
    private javax.swing.JTextField introducirPortNumber;
    private javax.swing.JTextField introducirServerName;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel login;
    private javax.swing.JLabel password;
    private javax.swing.JLabel portNumber;
    private javax.swing.JButton registro;
    private javax.swing.JLabel serverName;
    private javax.swing.JTextArea textAreaDebug;
    // End of variables declaration//GEN-END:variables
}
