/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import javax.swing.JTextArea;
import javax.swing.SwingWorker;

/**
 *
 * @author Jaime
 */
public class Metadatos extends javax.swing.JFrame {
    private String descripcion;
    private String tituloVideo;
    public static JTextArea textAreaDebug;

    public String getDescripcion() {
        return descripcion;
    }

    public String getTituloVideo() {
        return tituloVideo;
    }
    
    /**
     * Creates new form Metadatos
     * @param file
     */
    public Metadatos(JTextArea textAreaDebug) {
        initComponents();
        this.textAreaDebug = textAreaDebug;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        labelDescripcion = new javax.swing.JLabel();
        introducirDescripcion = new javax.swing.JTextField();
        enviarDatos = new javax.swing.JButton();
        tituloFrame = new javax.swing.JLabel();
        labelTituloVideo = new javax.swing.JLabel();
        introducirTitulo = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        labelDescripcion.setText("Descripción del video");
        getContentPane().add(labelDescripcion, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 150, 110, 20));
        getContentPane().add(introducirDescripcion, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 150, 100, -1));

        enviarDatos.setText("Subir");
        enviarDatos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                enviarDatosActionPerformed(evt);
            }
        });
        getContentPane().add(enviarDatos, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 230, 80, -1));

        tituloFrame.setText("Metadatos");
        getContentPane().add(tituloFrame, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 30, 60, 20));

        labelTituloVideo.setText("Titulo video");
        getContentPane().add(labelTituloVideo, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 80, 60, 20));
        getContentPane().add(introducirTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 80, 100, -1));

        jLabel1.setText("  ");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 310, 40, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void enviarDatosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_enviarDatosActionPerformed
        descripcion = introducirDescripcion.getText();
        tituloVideo = introducirTitulo.getText();
        final SwingWorker worker = new SwingWorker() {
            @Override
            protected Object doInBackground() throws Exception {
                Login.controller.subirVideo(textAreaDebug);
                return null;
            }
        };
        worker.execute();
    }//GEN-LAST:event_enviarDatosActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Metadatos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Metadatos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Metadatos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Metadatos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new Metadatos(textAreaDebug).setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton enviarDatos;
    private javax.swing.JTextField introducirDescripcion;
    private javax.swing.JTextField introducirTitulo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel labelDescripcion;
    private javax.swing.JLabel labelTituloVideo;
    private javax.swing.JLabel tituloFrame;
    // End of variables declaration//GEN-END:variables
}
