/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import Controlador.CristoTubeClientController;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JTextArea;

/**
 *
 * @author Jaime
 */
public class Registro extends javax.swing.JFrame {
    static CristoTubeClientController controller;
    static JTextArea textAreaDebug;
    /**
     * Creates new form Registro
     * @param controller
     */
    public Registro(CristoTubeClientController controller, JTextArea debug) {
        initComponents();
        this.controller = controller;
        this.textAreaDebug = debug;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        login = new javax.swing.JLabel();
        password = new javax.swing.JLabel();
        nombre = new javax.swing.JLabel();
        primerApellido = new javax.swing.JLabel();
        aceptar = new javax.swing.JButton();
        introducirLogin = new javax.swing.JTextField();
        introducirNombre = new javax.swing.JTextField();
        introducirPrimerApellido = new javax.swing.JTextField();
        titulo = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        segundoApellido = new javax.swing.JLabel();
        introducirSegundoApellido = new javax.swing.JTextField();
        dni = new javax.swing.JLabel();
        introducirDni = new javax.swing.JTextField();
        introducirPassword = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        login.setText("Login");
        getContentPane().add(login, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 260, 40, 20));

        password.setText("Password");
        getContentPane().add(password, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 310, 60, 20));

        nombre.setText("Nombre");
        getContentPane().add(nombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 110, 40, 20));

        primerApellido.setText("Apellido 1");
        getContentPane().add(primerApellido, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 160, 60, 20));

        aceptar.setText("Aceptar");
        aceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aceptarActionPerformed(evt);
            }
        });
        getContentPane().add(aceptar, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 370, -1, -1));
        getContentPane().add(introducirLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 260, 70, -1));
        getContentPane().add(introducirNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 110, 70, -1));
        getContentPane().add(introducirPrimerApellido, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 160, 70, -1));

        titulo.setText("Registrar nuevo usuario");
        getContentPane().add(titulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 20, -1, -1));
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 330, 20, 20));

        segundoApellido.setText("Apellido 2");
        getContentPane().add(segundoApellido, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 210, 60, 20));
        getContentPane().add(introducirSegundoApellido, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 210, 70, -1));

        dni.setText("DNI");
        getContentPane().add(dni, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 60, 40, 20));
        getContentPane().add(introducirDni, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 60, 70, -1));
        getContentPane().add(introducirPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 310, 70, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void aceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aceptarActionPerformed

        try {
            String cadenaRegistro = "PROTOCOLOCRISTOTUBE1.0#REGISTER#" + introducirDni.getText()
                    + "#" + introducirNombre.getText() + "#" + introducirPrimerApellido.getText()
                    + "#" + introducirSegundoApellido.getText() + "#" + introducirLogin.getText()
                    + "#" + introducirPassword.getText();
            controller.registrar(cadenaRegistro);
        } catch (IOException ex) {
            Logger.getLogger(Registro.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_aceptarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Registro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Registro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Registro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Registro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Registro(controller, textAreaDebug).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton aceptar;
    private javax.swing.JLabel dni;
    private javax.swing.JTextField introducirDni;
    private javax.swing.JTextField introducirLogin;
    private javax.swing.JTextField introducirNombre;
    private javax.swing.JPasswordField introducirPassword;
    private javax.swing.JTextField introducirPrimerApellido;
    private javax.swing.JTextField introducirSegundoApellido;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel login;
    private javax.swing.JLabel nombre;
    private javax.swing.JLabel password;
    private javax.swing.JLabel primerApellido;
    private javax.swing.JLabel segundoApellido;
    private javax.swing.JLabel titulo;
    // End of variables declaration//GEN-END:variables
}
