/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import java.io.IOException;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import javax.swing.SwingWorker;

/**
 *
 * @author Jaime
 */
public class Videos extends javax.swing.JFrame{
    static String lista;
    
    
    /**
     * Creates new form Videos
     * @param lista
     */
    public Videos(String lista) {
        initComponents();
        this.lista = lista;
        mostrar(this.lista);
    }

    public void mostrar(String cadena){   
        final SwingWorker worker = new SwingWorker() {
            @Override
            protected Object doInBackground() throws Exception {
                Login.controller.mostrarVideos(textAreaDebug, cadena, listaVideos);
                return null;
            }
        };
        worker.execute();
    }
    
    public void verVideo(){
        Login.terminarRecibir = false;
        String idVideo = (String) listaVideos.getModel().getValueAt(listaVideos.getSelectedRow(), 1);
        String login = (String) listaVideos.getModel().getValueAt(listaVideos.getSelectedRow(), 0);
        String nombreVideo = (String) listaVideos.getModel().getValueAt(listaVideos.getSelectedRow(), 2);
        String cadena = "PROTOCOLCRISTOTUBE1.0#" + login + "#GETVIDEO#" + idVideo;
        try {
            Login.controller.conectar(textAreaDebug, cadena);
        } catch (IOException ex) {
            System.out.println(ex);
        } catch (SQLException ex) {
            System.out.println(ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        listaVideos = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        textAreaDebug = new javax.swing.JTextArea();
        btnSubir = new javax.swing.JButton();
        btnVer = new javax.swing.JButton();
        btnBorrarVideo = new javax.swing.JButton();
        btnActualizar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        listaVideos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Usuario", "ID Video", "Titulo", "Descripción"
            }
        ));
        jScrollPane1.setViewportView(listaVideos);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 11, 880, 410));

        textAreaDebug.setColumns(20);
        textAreaDebug.setRows(5);
        jScrollPane2.setViewportView(textAreaDebug);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 536, 880, 80));

        btnSubir.setText("Subir video");
        btnSubir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSubirActionPerformed(evt);
            }
        });
        getContentPane().add(btnSubir, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 430, -1, -1));

        btnVer.setText("Ver video");
        btnVer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVerActionPerformed(evt);
            }
        });
        getContentPane().add(btnVer, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 460, -1, -1));

        btnBorrarVideo.setText("Borrar video");
        btnBorrarVideo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBorrarVideoActionPerformed(evt);
            }
        });
        getContentPane().add(btnBorrarVideo, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 460, -1, -1));

        btnActualizar.setText("Actualizar");
        btnActualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActualizarActionPerformed(evt);
            }
        });
        getContentPane().add(btnActualizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 500, 90, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSubirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSubirActionPerformed
        JFileChooser elegirVideo = new JFileChooser();
        elegirVideo.showOpenDialog(this);
        final SwingWorker worker = new SwingWorker() {
            @Override
            protected Object doInBackground() throws Exception {
                Login.controller.addMetadatos(elegirVideo, textAreaDebug);
                return null;
            }
        };
        worker.execute();
    }//GEN-LAST:event_btnSubirActionPerformed

    private void btnVerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVerActionPerformed
        final SwingWorker worker = new SwingWorker() {
            @Override
            protected Object doInBackground() throws Exception {
                verVideo();
                return null;
            }
        };
        worker.execute();
    }//GEN-LAST:event_btnVerActionPerformed

    private void btnBorrarVideoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBorrarVideoActionPerformed
        String idVideo = (String) listaVideos.getModel().getValueAt(listaVideos.getSelectedRow(), 1);
        final SwingWorker worker = new SwingWorker() {
            @Override
            protected Object doInBackground() throws Exception {
                Login.controller.borrarVideo(idVideo, textAreaDebug);
                return null;
            }
        };
        worker.execute();
    }//GEN-LAST:event_btnBorrarVideoActionPerformed

    private void btnActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActualizarActionPerformed
        final SwingWorker worker = new SwingWorker() {
            @Override
            protected Object doInBackground() throws Exception {
                Login.controller.actualizarTabla(textAreaDebug);
                return null;
            }
        };
        worker.execute();
    }//GEN-LAST:event_btnActualizarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Videos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Videos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Videos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Videos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new Videos(lista).setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnActualizar;
    private javax.swing.JButton btnBorrarVideo;
    private javax.swing.JButton btnSubir;
    private javax.swing.JButton btnVer;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable listaVideos;
    private javax.swing.JTextArea textAreaDebug;
    // End of variables declaration//GEN-END:variables

}
