package Modelo;
// Generated 01-feb-2018 20:17:57 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Tablausuarios generated by hbm2java
 */
public class Tablausuarios  implements java.io.Serializable {


     private Integer id;
     private String dni;
     private String nombre;
     private String apellido1;
     private String apellido2;
     private String login;
     private String password;
     private Set videoses = new HashSet(0);

    public Tablausuarios() {
    }

	
    public Tablausuarios(String dni, String nombre, String apellido1, String apellido2, String login, String password) {
        this.dni = dni;
        this.nombre = nombre;
        this.apellido1 = apellido1;
        this.apellido2 = apellido2;
        this.login = login;
        this.password = password;
    }
    public Tablausuarios(String dni, String nombre, String apellido1, String apellido2, String login, String password, Set videoses) {
       this.dni = dni;
       this.nombre = nombre;
       this.apellido1 = apellido1;
       this.apellido2 = apellido2;
       this.login = login;
       this.password = password;
       this.videoses = videoses;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getDni() {
        return this.dni;
    }
    
    public void setDni(String dni) {
        this.dni = dni;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getApellido1() {
        return this.apellido1;
    }
    
    public void setApellido1(String apellido1) {
        this.apellido1 = apellido1;
    }
    public String getApellido2() {
        return this.apellido2;
    }
    
    public void setApellido2(String apellido2) {
        this.apellido2 = apellido2;
    }
    public String getLogin() {
        return this.login;
    }
    
    public void setLogin(String login) {
        this.login = login;
    }
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }
    public Set getVideoses() {
        return this.videoses;
    }
    
    public void setVideoses(Set videoses) {
        this.videoses = videoses;
    }




}


