package Modelo;
// Generated 01-feb-2018 20:17:57 by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Videos generated by hbm2java
 */
public class Videos  implements java.io.Serializable {


     private Integer idvideo;
     private Tablausuarios tablausuarios;
     private String rutaserver;
     private String titulo;
     private Date fecha;
     private String descripcion;

    public Videos() {
    }

    public Videos(Tablausuarios tablausuarios, String rutaserver, String titulo, Date fecha, String descripcion) {
       this.tablausuarios = tablausuarios;
       this.rutaserver = rutaserver;
       this.titulo = titulo;
       this.fecha = fecha;
       this.descripcion = descripcion;
    }
   
    public Integer getIdvideo() {
        return this.idvideo;
    }
    
    public void setIdvideo(Integer idvideo) {
        this.idvideo = idvideo;
    }
    public Tablausuarios getTablausuarios() {
        return this.tablausuarios;
    }
    
    public void setTablausuarios(Tablausuarios tablausuarios) {
        this.tablausuarios = tablausuarios;
    }
    public String getRutaserver() {
        return this.rutaserver;
    }
    
    public void setRutaserver(String rutaserver) {
        this.rutaserver = rutaserver;
    }
    public String getTitulo() {
        return this.titulo;
    }
    
    public void setTitulo(String titulo) {
        this.titulo = titulo;
    }
    public Date getFecha() {
        return this.fecha;
    }
    
    public void setFecha(Date fecha) {
        this.fecha = fecha;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }




}


